language: node_js
node_js:
  - "node"
cache:
  - yarn: true
  - bundler: true
  - directories:
    - node_modules
    - /home/travis/.rvm/
before_install:
  - rvm install 2.5.0
  - gem install bundler

install:
  - yarn install
  - bundle install
script:
  - yarn test
  - bundle exec rake assets:precompile
  - bundle exec rake db:create db:schema:load db:test:prepare
  - bundle exec rake test
  - bundle exec rubocop
notifications:
  email: false
